before_script:
  # Exit on errors.
  - set -e
  
  # Update composer
  - composer self-update

  # Install Behat
  - cd ./behat
  - cp behat.local.yml.example behat.local.yml
  - composer install

script:
  - ./bin/behat --tags=~wip
